AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kehrwoche Poller service'
Parameters:
  Version:
    Type: String
Resources:
  EventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "KehrwocheEvents"
      KeySchema:
        - AttributeName: "area"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "area"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
  FunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 'ses:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'dynamodb:*'
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::Account}:table/${EventsTable}
  Function:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      Role: !GetAtt [FunctionRole, Arn]
      Code:
        S3Bucket: !Sub taimos-lambda-public-${AWS::Region}
        S3Key: !Sub kehrwoche-poller-${Version}.zip
      Runtime: nodejs4.3
      Timeout: '300'
  CronRule:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: 'rate(1 minute)'
      Targets:
        - Id: PollerScheduler
          Arn: !GetAtt [Function, Arn]
  InvokeLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt [Function, Arn]
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CronRule, Arn]
Outputs:
  LambdaFunction:
    Description: 'The ARN of the Lambda'
    Value: !GetAtt [Function, Arn]